version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm install
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate
      - persist_to_workspace:
          root: public
          paths:
            - "*"
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - "8f:6d:7c:32:22:32:67:9f:0c:40:a2:fe:9a:d6:35:d1"
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            hexo clean
            hexo generate --deploy
  # verify:
  #   docker:
  #     - image: circleci/node:16
  #   steps:
  #     - run:
  #         name: Install BLC
  #         command: sudo npm install -g broken-link-checker
  #     - run:
  #         name: Check broken internal links
  #         command: blc https://e.printstacktrace.blog -roe

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
      - verify:
          requires:
            - deploy