name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  16.11.0

        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Clean install dependencies
          run: npm install

        - name: Clean and Build app
          run: npm run clean && npm run build

        - name: deploy to github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
           publish_dir: ./public