name: Hexo CI CD
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 
        with:
          persist-credentials: false
          submodules: recursive
      - name: "Using Special Node Version"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Generate Hexo site ⚗️
        run: |
          echo "Github Action Env Checking..."
          echo "Node Version: `node -v`"
          # Install dependencies && update env
          echo "Install npm dependencies"
          npm i
          echo "Load hexo binary..."
          export PATH="$PATH:./node_modules/.bin"
          echo "Hexo version: $(hexo -v)"
          # Generate site && minify site files, such as: html, js, css
          hexo g --debug

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted 
          PRESERVE: true